openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of AquaTrack
tags:
  - name: Users
    description: Operations about users.
  - name: Water consumption
    description: Operations about water consumption.
servers:
  - url: http://localhost:3000
  - url: https://aquatrack-backend-bmxm.onrender.com
paths:
  # /users/{id}:
  #   get:
  #     $ref: ./paths/users/{id}/get.yaml
  #   patch:
  #     $ref: ./paths/users/{id}/patch.yaml
  /users/signup:
    post:
      $ref: ../swagger/paths/users/signup/post.yaml
  /users/signin:
    post:
      $ref: ../swagger/paths/users/signin/post.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout/post.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/refresh/post.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/update/patch.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    put:
      $ref: ../swagger/paths/water/{id}/put.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/day/{date}:
    get:
      $ref: ../swagger/paths/water/day/{date}/get.yaml
  /water/month/{month}:
    get:
      $ref: ../swagger/paths/water/month/{month}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
